---
/detect_traffic_light:
  ros__parameters:
        red:
          hue_l: 0
          hue_h: 16
          saturation_l: 59
          saturation_h: 255
          lightness_l: 162
          lightness_h: 255
        yellow:
          hue_l: 16
          hue_h: 40
          saturation_l: 59
          saturation_h: 255
          lightness_l: 162
          lightness_h: 255
        green:
          hue_l: 40
          hue_h: 113
          saturation_l: 71
          saturation_h: 255
          lightness_l: 131
          lightness_h: 255
